[package]
name = "game_input"
version = "0.1.0"
authors = ["TehPers <tehperz@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.4"
tracing = "0.1"

game_camera = { path = "../game_camera" }
game_core = { path = "../game_core" }
