[package]
name = "game_controller"
version = "0.1.0"
authors = ["TehPers <tehperz@gmail.com>"]
edition = "2018"

[dependencies]
game_lib = "*"
game_camera = "*"
game_input = "*"
game_physics = "*"
game_core = "*"
game_tiles = "*"
