[package]
name = "game_wasi"
version = "0.1.0"
authors = ["TehPers <tehperz@gmail.com>"]
edition = "2018"

[dependencies]
game_lib = "*"
game_core = "*"
wasmer = "1"
wasmer-wasi = "1"
semver = { version = "0.11", features = ["serde"] }
