[package]
name = "game_tiles"
version = "0.1.0"
authors = ["TehPers <tehperz@gmail.com>"]
edition = "2018"

[dependencies]
array-init = "2"
game_lib = "*"
game_core = "*"
game_morton = "*"
game_camera = "*"
